/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controller.AgendamentoController;
import Controller.ServicesController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Biel
 */
public class Agendar extends javax.swing.JFrame {

    private AgendamentoController controller;

    public Agendar(AgendamentoController controller) {
        this.controller = controller;
    }

    
    /**
     * Creates new form Agendar
     */
    public Agendar() {
        initComponents();
        controller = new AgendamentoController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VarCorte = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TextName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        labelhorario = new javax.swing.JLabel();
        VarPrice = new javax.swing.JTextField();
        labelservice = new javax.swing.JLabel();
        ComboBoxService = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelhorario1 = new javax.swing.JLabel();
        VarHora = new javax.swing.JComboBox();
        VarData = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        VarObeservacao = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        VarName = new javax.swing.JTextField();
        VarEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        labelemail = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        VarTelefone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 140));
        jPanel2.setForeground(new java.awt.Color(244, 244, 244));

        TextName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextName.setAlignmentX(0.0F);
        TextName.setBorder(null);
        TextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefone");

        label.setBackground(new java.awt.Color(255, 255, 255));
        label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setText("Data:");

        labelhorario.setBackground(new java.awt.Color(255, 255, 255));
        labelhorario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelhorario.setForeground(new java.awt.Color(255, 255, 255));
        labelhorario.setText("Horario:");

        VarPrice.setEditable(false);
        VarPrice.setBackground(new java.awt.Color(255, 255, 255));
        VarPrice.setForeground(new java.awt.Color(0, 0, 0));
        VarPrice.setText("asdadasdadadadaasdadsda");
        VarPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VarPriceActionPerformed(evt);
            }
        });

        labelservice.setBackground(new java.awt.Color(255, 255, 255));
        labelservice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelservice.setForeground(new java.awt.Color(255, 255, 255));
        labelservice.setText("Serviço:");

        ComboBoxService.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComboBoxService.setForeground(new java.awt.Color(255, 255, 255));
        ComboBoxService.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..." }));
        ComboBoxService.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ComboBoxServiceAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ComboBoxService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxServiceActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecione o serviço...");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        labelhorario1.setBackground(new java.awt.Color(255, 255, 255));
        labelhorario1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelhorario1.setForeground(new java.awt.Color(255, 255, 255));
        labelhorario1.setText("Preço:");

        VarHora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        VarHora.setForeground(new java.awt.Color(255, 255, 255));
        VarHora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione a Hora..." }));
        VarHora.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                VarHoraAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        VarHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VarHoraActionPerformed(evt);
            }
        });

        VarData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        VarData.setForeground(new java.awt.Color(255, 255, 255));
        VarData.setMaximumRowCount(20);
        VarData.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o Dia..." }));
        VarData.setToolTipText("");
        VarData.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                VarDataAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        VarData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VarDataActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 153, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Agendar");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setMaximumSize(new java.awt.Dimension(32, 16));
        jButton2.setMinimumSize(new java.awt.Dimension(32, 16));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        VarObeservacao.setColumns(20);
        VarObeservacao.setRows(5);
        jScrollPane1.setViewportView(VarObeservacao);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Observação");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ViewsImagens/Logo (2).png"))); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelservice, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200)
                                .addComponent(labelhorario1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ComboBoxService, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(VarData, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(VarHora, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelhorario, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(VarPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel7)
                        .addGap(561, 561, 561)
                        .addComponent(TextName, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(399, 399, 399)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(TextName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel7)))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(VarData, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(labelhorario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VarHora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelservice)
                    .addComponent(labelhorario1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxService, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VarPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 590, 660));

        VarName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        VarName.setText("SDAADAWD");
        VarName.setAlignmentX(0.0F);
        VarName.setBorder(null);
        VarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VarNameActionPerformed(evt);
            }
        });
        getContentPane().add(VarName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 930, 185, 40));

        VarEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        VarEmail.setText("adwad");
        VarEmail.setAlignmentX(0.0F);
        VarEmail.setBorder(null);
        VarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VarEmailActionPerformed(evt);
            }
        });
        getContentPane().add(VarEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 940, 204, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefone:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 910, -1, -1));

        labelemail.setBackground(new java.awt.Color(255, 255, 255));
        labelemail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelemail.setForeground(new java.awt.Color(255, 255, 255));
        labelemail.setText("E-mail:");
        getContentPane().add(labelemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 890, 81, 28));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 910, -1, -1));

        VarTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        VarTelefone.setAlignmentX(0.0F);
        VarTelefone.setBorder(null);
        VarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VarTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(VarTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 940, 185, 36));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("JP BARBEARIA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        jMenu2.setText("Ações");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

            // TODO add your handling code here:
            controller.salvarAgendamento();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ComboBoxServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxServiceActionPerformed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_ComboBoxServiceActionPerformed

    private void VarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VarTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VarTelefoneActionPerformed

    private void VarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VarEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VarEmailActionPerformed

    private void VarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VarNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VarNameActionPerformed

    private void VarPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VarPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VarPriceActionPerformed

    private void ComboBoxServiceAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ComboBoxServiceAncestorAdded
        try {
            // TODO add your handling code here:
            controller.ComboboxService();
        } catch (SQLException ex) {
            Logger.getLogger(Agendar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComboBoxServiceAncestorAdded

    private void VarHoraAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_VarHoraAncestorAdded
        try {
            // TODO add your handling code here:
            controller.AdicionandoHoras();
        } catch (SQLException ex) {
            Logger.getLogger(Agendar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_VarHoraAncestorAdded

    private void VarDataAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_VarDataAncestorAdded
        // TODO add your handling code here:
        controller.AdicionandoData();
    }//GEN-LAST:event_VarDataAncestorAdded

    private void VarHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VarHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VarHoraActionPerformed

    private void VarDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VarDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VarDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agendar().setVisible(true);
            }
        });
    }

    public JComboBox<String> getComboBoxService() {
        return ComboBoxService;
    }

    public void setComboBoxService(JComboBox<String> ComboBoxService) {
        this.ComboBoxService = ComboBoxService;
    }

    public JLabel getVarCorte() {
        return VarCorte;
    }

    public void setVarCorte(JLabel VarCorte) {
        this.VarCorte = VarCorte;
    }

   
    public JTextField getVarEmail() {
        return VarEmail;
    }

    public void setVarEmail(JTextField VarEmail) {
        this.VarEmail = VarEmail;
    }

    public JComboBox getVarData() {
        return VarData;
    }

    public void setVarData(JComboBox VarData) {
        this.VarData = VarData;
    }
    

    public JComboBox<String> getVarHora() {
        return VarHora;
    }

    public void setVarHora(JComboBox<String> VarHora) {
        this.VarHora = VarHora;
    }

    public JTextField getVarTelefone() {
        return VarTelefone;
    }

    public void setVarTelefone(JTextField VarTelefone) {
        this.VarTelefone = VarTelefone;
    }

   
    public JTextField getVarName() {
        return VarName;
    }

    public void setVarName(JTextField VarName) {
        this.VarName = VarName;
    }

    public JTextArea getVarObeservacao() {
        return VarObeservacao;
    }

    public void setVarObeservacao(JTextArea VarObeservacao) {
        this.VarObeservacao = VarObeservacao;
    }

    public JTextField getVarPrice() {
        return VarPrice;
    }

    public void setVarPrice(JTextField VarPrice) {
        this.VarPrice = VarPrice;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxService;
    private javax.swing.JTextField TextName;
    private javax.swing.JLabel VarCorte;
    private javax.swing.JComboBox VarData;
    private javax.swing.JTextField VarEmail;
    private javax.swing.JComboBox VarHora;
    private javax.swing.JTextField VarName;
    private javax.swing.JTextArea VarObeservacao;
    private javax.swing.JTextField VarPrice;
    private javax.swing.JTextField VarTelefone;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel labelemail;
    private javax.swing.JLabel labelhorario;
    private javax.swing.JLabel labelhorario1;
    private javax.swing.JLabel labelservice;
    // End of variables declaration//GEN-END:variables
}

