/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controller.AgendamentoController;
import Controller.BarbeiroController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author Biel
 */
public class MenuBarbeiro extends javax.swing.JFrame {

    private BarbeiroController controller;
    private  AgendamentoController agendamentoController;
    private MenuBarbeiro menu;

    public MenuBarbeiro(BarbeiroController controller) {
        this.controller = controller;
    }
    
    /**
     * Creates new form MenuBarbeiro
     */
    public MenuBarbeiro() throws SQLException {
        initComponents();
        controller = new BarbeiroController(this);
        agendamentoController = new AgendamentoController(this);
        iniciarTable();
    }
    
     private void iniciarTable() throws SQLException {
         controller.atualizarTabelaAgendamento();
    }
     
   

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableAgendamentos = new javax.swing.JTable();
        TodosAgendamentos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        AgendamentoHistorico = new javax.swing.JButton();
        Welcome = new javax.swing.JLabel();
        AgendamentoHoje = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableAgendamentos.setBackground(new java.awt.Color(255, 255, 255));
        TableAgendamentos.setForeground(new java.awt.Color(0, 0, 0));
        TableAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "whats", "Serviço", "Data", "Hora", "Preço", "Obser"
            }
        ));
        jScrollPane1.setViewportView(TableAgendamentos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 910, 330));

        TodosAgendamentos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TodosAgendamentos.setForeground(new java.awt.Color(255, 255, 255));
        TodosAgendamentos.setText("Em Dia");
        TodosAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodosAgendamentosActionPerformed(evt);
            }
        });
        getContentPane().add(TodosAgendamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 70, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, 30));

        AgendamentoHistorico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgendamentoHistorico.setForeground(new java.awt.Color(255, 255, 255));
        AgendamentoHistorico.setText("Historico");
        AgendamentoHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendamentoHistoricoActionPerformed(evt);
            }
        });
        getContentPane().add(AgendamentoHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, 30));

        Welcome.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Welcome.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 290, 30));

        AgendamentoHoje.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgendamentoHoje.setForeground(new java.awt.Color(255, 255, 255));
        AgendamentoHoje.setText("Hoje");
        AgendamentoHoje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendamentoHojeActionPerformed(evt);
            }
        });
        getContentPane().add(AgendamentoHoje, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agendamentos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ViewsImagens/BannerPC.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 490));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        jMenu2.setText("Edit");

        jMenuItem2.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ViewsIcons/tesoura-icon.png"))); // NOI18N
        jMenuItem2.setText("Serviços");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ViewsIcons/usuario-icon.png"))); // NOI18N
        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem1.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ViewsIcons/cliente-icon.png"))); // NOI18N
        jMenuItem1.setText("Novo Acesso");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem4.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ViewsIcons/agenda-icon.png"))); // NOI18N
        jMenuItem4.setText("Agendar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            // TODO add your handling code here:
            TelaService services = new TelaService();
            services.setVisible(true);
            setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MenuBarbeiro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        LoginBarbeiro login = new LoginBarbeiro();
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        CadastrarBarbeiro cadastrar = new CadastrarBarbeiro();
        cadastrar.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void TodosAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodosAgendamentosActionPerformed
        try {
            // TODO add your handling code here:
            controller.filtrarTodos();
        } catch (SQLException ex) {
            Logger.getLogger(MenuBarbeiro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TodosAgendamentosActionPerformed

    private void AgendamentoHojeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendamentoHojeActionPerformed
        try {
            // TODO add your handling code here:
            controller.filtrarAgendamentosHoje();
        } catch (SQLException ex) {
            Logger.getLogger(MenuBarbeiro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AgendamentoHojeActionPerformed

    private void AgendamentoHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendamentoHistoricoActionPerformed
        try {
            // TODO add your handling code here:
            controller.atualizarHistoricodaTabela();
        } catch (SQLException ex) {
            Logger.getLogger(MenuBarbeiro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AgendamentoHistoricoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        agendamentoController.ExcluirAgendamento();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        TelaAgendamentoBarbeiro agendar = new TelaAgendamentoBarbeiro();
        agendar.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBarbeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBarbeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBarbeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBarbeiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MenuBarbeiro().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MenuBarbeiro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public JTable getTableAgendamentos() {
        return TableAgendamentos;
    }

    public void setTableAgendamentos(JTable TableAgendamentos) {
        this.TableAgendamentos = TableAgendamentos;
    }
     public JLabel getWelcome() {
        return Welcome;
    }

    public void setWelcome(JLabel Welcome) {
        this.Welcome = Welcome;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgendamentoHistorico;
    private javax.swing.JButton AgendamentoHoje;
    private javax.swing.JTable TableAgendamentos;
    private javax.swing.JButton TodosAgendamentos;
    private javax.swing.JLabel Welcome;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
